CREATE TABLE ingesoft.adjunto (
  cod_adjunto     NUMBER GENERATED BY DEFAULT AS IDENTITY,
  nombre_archivo  VARCHAR2(200) NOT NULL,
  mime_type       VARCHAR2(100),
  tamanio_bytes   NUMBER,
  contenido_blob  BLOB
);

ALTER TABLE ingesoft.adjunto ADD CONSTRAINT pk_adjunto PRIMARY KEY (cod_adjunto);
