CREATE TABLE ingesoft.aporte_ips (
  cod_aporte_ips  NUMBER GENERATED BY DEFAULT AS IDENTITY,
  proceso_id      NUMBER NOT NULL,
  empleado_id     NUMBER NOT NULL,
  base_imponible  NUMBER(14,2) NOT NULL,
  porc_empleado   NUMBER(5,2)  DEFAULT 9.00,
  monto_empleado  NUMBER(14,2) NOT NULL,
  porc_empleador  NUMBER(5,2),
  monto_empleador NUMBER(14,2)
);

ALTER TABLE ingesoft.aporte_ips ADD CONSTRAINT pk_aporte_ips PRIMARY KEY (cod_aporte_ips);
ALTER TABLE ingesoft.aporte_ips ADD CONSTRAINT fk_ips_proceso  FOREIGN KEY (proceso_id)  REFERENCES ingesoft.proceso_nomina(cod_proceso_nomina);
ALTER TABLE ingesoft.aporte_ips ADD CONSTRAINT fk_ips_empleado FOREIGN KEY (empleado_id) REFERENCES ingesoft.empleado(cod_empleado);

CREATE INDEX ingesoft.ix_ips_empleado         ON ingesoft.aporte_ips(empleado_id);