
  CREATE TABLE "APX_NAVIGATION_MENU" 
   (	"APPLICATION_ID" NUMBER NOT NULL ENABLE, 
	"MENU_ITEM_ID" NUMBER NOT NULL ENABLE, 
	"WORKSPACE" VARCHAR2(100) NOT NULL ENABLE, 
	"MENU_LEVEL" NUMBER NOT NULL ENABLE, 
	"LABEL" VARCHAR2(200) NOT NULL ENABLE, 
	"TARGET_TYPE" VARCHAR2(20) DEFAULT 'APEX' NOT NULL ENABLE, 
	"TARGET_APP_ID" NUMBER, 
	"TARGET_PAGE_ID" VARCHAR2(50), 
	"TARGET_REQUEST" VARCHAR2(100), 
	"TARGET_CLEAR" VARCHAR2(100), 
	"TARGET_ITEMS" VARCHAR2(500), 
	"TARGET_VALUES" VARCHAR2(500), 
	"TARGET_URL" VARCHAR2(1000), 
	"TARGET_JS" VARCHAR2(1000), 
	"IS_CURRENT" VARCHAR2(3) DEFAULT 'NO', 
	"IMAGE_ICON" VARCHAR2(100), 
	"IMAGE_ATTRIBUTE" VARCHAR2(500), 
	"IMAGE_ALT_ATTRIBUTE" VARCHAR2(500), 
	"ATTRIBUTE_01" VARCHAR2(500), 
	"ATTRIBUTE_02" VARCHAR2(500), 
	"ATTRIBUTE_03" VARCHAR2(500), 
	"ATTRIBUTE_04" VARCHAR2(500), 
	"ATTRIBUTE_05" VARCHAR2(500), 
	"ATTRIBUTE_06" VARCHAR2(500), 
	"ATTRIBUTE_07" VARCHAR2(500), 
	"ATTRIBUTE_08" VARCHAR2(500), 
	"ATTRIBUTE_09" VARCHAR2(500), 
	"ATTRIBUTE_10" VARCHAR2(500), 
	"PARENT_APPLICATION_ID" NUMBER, 
	"PARENT_MENU_ITEM_ID" NUMBER, 
	"DISPLAY_ORDER" NUMBER DEFAULT 999 NOT NULL ENABLE, 
	"IS_VISIBLE" VARCHAR2(1) DEFAULT 'Y' NOT NULL ENABLE, 
	"IS_ACTIVE" VARCHAR2(1) DEFAULT 'Y' NOT NULL ENABLE, 
	"CODIGO_PERMISO" VARCHAR2(60), 
	"DESCRIPCION" VARCHAR2(1000), 
	"FECHA_CREACION" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"FECHA_MODIFICACION" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	 CONSTRAINT "PK_APX_NAVIGATION_MENU" PRIMARY KEY ("APPLICATION_ID", "MENU_ITEM_ID", "WORKSPACE")
  USING INDEX  ENABLE, 
	 CONSTRAINT "CHK_APX_MENU_IS_VISIBLE" CHECK (IS_VISIBLE IN ('Y', 'N')) ENABLE, 
	 CONSTRAINT "CHK_APX_MENU_IS_ACTIVE" CHECK (IS_ACTIVE IN ('Y', 'N')) ENABLE, 
	 CONSTRAINT "CHK_APX_MENU_IS_CURRENT" CHECK (IS_CURRENT IN ('YES', 'NO')) ENABLE, 
	 CONSTRAINT "CHK_APX_MENU_TARGET_TYPE" CHECK (TARGET_TYPE IN ('APEX', 'URL', 'JS', 'NONE')) ENABLE, 
	 CONSTRAINT "CHK_TARGET_REQUIRED" CHECK (
    (TARGET_TYPE = 'APEX' AND TARGET_APP_ID IS NOT NULL) OR
    (TARGET_TYPE = 'URL' AND TARGET_URL IS NOT NULL) OR
    (TARGET_TYPE = 'JS' AND TARGET_JS IS NOT NULL) OR
    (TARGET_TYPE = 'NONE')
  ) ENABLE
   ) ;

  CREATE INDEX "IDX_APX_MENU_HIERARCHY" ON "APX_NAVIGATION_MENU" ("APPLICATION_ID", "PARENT_APPLICATION_ID", "PARENT_MENU_ITEM_ID", "MENU_LEVEL", "DISPLAY_ORDER") 
  ;

  CREATE INDEX "IDX_APX_MENU_LEVEL" ON "APX_NAVIGATION_MENU" ("MENU_LEVEL", "DISPLAY_ORDER") 
  ;

  CREATE INDEX "IDX_APX_MENU_PARENT" ON "APX_NAVIGATION_MENU" ("PARENT_APPLICATION_ID", "PARENT_MENU_ITEM_ID") 
  ;

  CREATE INDEX "IDX_APX_MENU_PERMISO" ON "APX_NAVIGATION_MENU" ("CODIGO_PERMISO") 
  ;

  CREATE INDEX "IDX_APX_MENU_VISIBLE" ON "APX_NAVIGATION_MENU" ("IS_VISIBLE", "IS_ACTIVE") 
  ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_APX_NAVIGATION_MENU" 
  BEFORE INSERT OR UPDATE ON INGESOFT.APX_NAVIGATION_MENU
  FOR EACH ROW
BEGIN
  :NEW.FECHA_MODIFICACION := SYSDATE;
END;
/
ALTER TRIGGER "TRG_APX_NAVIGATION_MENU" ENABLE;