CREATE TABLE ingesoft.auditoria (
  cod_auditoria NUMBER GENERATED BY DEFAULT AS IDENTITY,
  usuario_id    NUMBER,
  accion        VARCHAR2(60)  NOT NULL,
  objeto        VARCHAR2(120),
  objeto_id     VARCHAR2(120),
  fecha_evento  DATE,
  detalles      CLOB
);

ALTER TABLE ingesoft.auditoria ADD CONSTRAINT pk_auditoria PRIMARY KEY (cod_auditoria);
ALTER TABLE ingesoft.auditoria ADD CONSTRAINT fk_aud_usuario FOREIGN KEY (usuario_id) REFERENCES ingesoft.usuario(cod_usuario);
