CREATE TABLE ingesoft.ausencia (
  cod_ausencia  NUMBER GENERATED BY DEFAULT AS IDENTITY,
  empleado_id   NUMBER NOT NULL,
  fecha_desde   DATE   NOT NULL,
  fecha_hasta   DATE   NOT NULL,
  tipo_id       NUMBER NOT NULL,
  horas         NUMBER(6,2)
);

ALTER TABLE ingesoft.ausencia ADD CONSTRAINT pk_ausencia PRIMARY KEY (cod_ausencia);
ALTER TABLE ingesoft.ausencia ADD CONSTRAINT fk_ausencia_empleado FOREIGN KEY (empleado_id) REFERENCES ingesoft.empleado(cod_empleado);
ALTER TABLE ingesoft.ausencia ADD CONSTRAINT fk_ausencia_tipo FOREIGN KEY (tipo_id) REFERENCES ingesoft.tipo_ausencia(cod_tipo_ausencia);

CREATE INDEX ingesoft.ix_ausencia_empleado    ON ingesoft.ausencia(empleado_id);