CREATE TABLE ingesoft.cargo (
  cod_cargo        NUMBER GENERATED BY DEFAULT AS IDENTITY,
  departamento_id  NUMBER        NOT NULL,
  nombre           VARCHAR2(120) NOT NULL,
  nivel            VARCHAR2(50),
  activo           VARCHAR2(1)   DEFAULT 'S' NOT NULL
);

ALTER TABLE ingesoft.cargo ADD CONSTRAINT pk_cargo PRIMARY KEY (cod_cargo);
ALTER TABLE ingesoft.cargo ADD CONSTRAINT uq_cargo_nombre UNIQUE (nombre);
ALTER TABLE ingesoft.cargo ADD CONSTRAINT ck_cargo_activo CHECK (activo IN ('S','N'));
ALTER TABLE ingesoft.cargo ADD CONSTRAINT fk_cargo_departamento
  FOREIGN KEY (departamento_id) REFERENCES ingesoft.departamento(cod_departamento);