CREATE TABLE ingesoft.concepto_regla (
  cod_concepto_regla NUMBER GENERATED BY DEFAULT AS IDENTITY,
  concepto_id        NUMBER NOT NULL,
  formula            CLOB,
  activo             VARCHAR2(1) DEFAULT 'S' NOT NULL
);

ALTER TABLE ingesoft.concepto_regla ADD CONSTRAINT pk_concepto_regla PRIMARY KEY (cod_concepto_regla);
ALTER TABLE ingesoft.concepto_regla ADD CONSTRAINT ck_concepto_regla_activo CHECK (activo IN ('S','N'));
ALTER TABLE ingesoft.concepto_regla ADD CONSTRAINT fk_concepto_regla_concepto FOREIGN KEY (concepto_id) REFERENCES ingesoft.concepto(cod_concepto);
