CREATE TABLE ingesoft.concepto (
  cod_concepto       NUMBER GENERATED BY DEFAULT AS IDENTITY,
  codigo             VARCHAR2(30)  NOT NULL,
  descripcion        VARCHAR2(150) NOT NULL,
  tipo               VARCHAR2(10)  NOT NULL,
  recurrente         VARCHAR2(1)   DEFAULT 'S' NOT NULL,
  afecta_ips         VARCHAR2(1)   DEFAULT 'S' NOT NULL,
  afecta_aguinaldo   VARCHAR2(1)   DEFAULT 'S' NOT NULL,
  inembargable       VARCHAR2(1)   DEFAULT 'N' NOT NULL
);

ALTER TABLE ingesoft.concepto ADD CONSTRAINT pk_concepto PRIMARY KEY (cod_concepto);
ALTER TABLE ingesoft.concepto ADD CONSTRAINT uq_concepto_codigo UNIQUE (codigo);
ALTER TABLE ingesoft.concepto ADD CONSTRAINT ck_concepto_tipo CHECK (tipo IN ('INGRESO','DESCUENTO'));
ALTER TABLE ingesoft.concepto ADD CONSTRAINT ck_concepto_flags CHECK (
  recurrente IN ('S','N') AND afecta_ips IN ('S','N') AND afecta_aguinaldo IN ('S','N') AND inembargable IN ('S','N')
);