CREATE TABLE ingesoft.departamento (
cod_departamento NUMBER GENERATED BY DEFAULT AS IDENTITY,
nombre VARCHAR2(100) NOT NULL,
activo VARCHAR2(1) DEFAULT 'S' NOT NULL
);


ALTER TABLE ingesoft.departamento ADD CONSTRAINT pk_departamento PRIMARY KEY (cod_departamento);
ALTER TABLE ingesoft.departamento ADD CONSTRAINT uq_departamento_nombre UNIQUE (nombre);
ALTER TABLE ingesoft.departamento ADD CONSTRAINT ck_departamento_activo CHECK (activo IN ('S','N'));