CREATE TABLE ingesoft.descuento_judicial (
  cod_descuento_judicial NUMBER GENERATED BY DEFAULT AS IDENTITY,
  empleado_id     NUMBER NOT NULL,
  juzgado         VARCHAR2(150),
  expediente      VARCHAR2(80),
  porc_sobre_neto NUMBER(6,3),
  monto_fijo_gs   NUMBER(14,2),
  vigente_desde   DATE NOT NULL,
  vigente_hasta   DATE
);

ALTER TABLE ingesoft.descuento_judicial ADD CONSTRAINT pk_descuento_judicial PRIMARY KEY (cod_descuento_judicial);
ALTER TABLE ingesoft.descuento_judicial ADD CONSTRAINT fk_descjud_empleado FOREIGN KEY (empleado_id) REFERENCES ingesoft.empleado(cod_empleado);
