CREATE TABLE ingesoft.empleado (
  cod_empleado     NUMBER GENERATED BY DEFAULT AS IDENTITY,
  persona_id       NUMBER NOT NULL,
  fecha_ingreso    DATE   NOT NULL,
  fecha_egreso     DATE,
  ips_nro_asegurado VARCHAR2(30),
  cargo_id         NUMBER,
  activo           VARCHAR2(1) DEFAULT 'S' NOT NULL
);

ALTER TABLE ingesoft.empleado ADD CONSTRAINT pk_empleado PRIMARY KEY (cod_empleado);
ALTER TABLE ingesoft.empleado ADD CONSTRAINT uq_empleado_persona UNIQUE (persona_id);
ALTER TABLE ingesoft.empleado ADD CONSTRAINT ck_empleado_activo CHECK (activo IN ('S','N'));
ALTER TABLE ingesoft.empleado ADD CONSTRAINT fk_empleado_persona
  FOREIGN KEY (persona_id) REFERENCES ingesoft.persona(cod_persona);
ALTER TABLE ingesoft.empleado ADD CONSTRAINT fk_empleado_cargo
  FOREIGN KEY (cargo_id) REFERENCES ingesoft.cargo(cod_cargo);

CREATE INDEX ingesoft.ix_empleado_cargo       ON ingesoft.empleado(cargo_id);
CREATE INDEX ingesoft.ix_empleado_persona     ON ingesoft.empleado(persona_id);