CREATE TABLE ingesoft.empleado_cargo_hist (
  cod_empleado_cargo_hist NUMBER GENERATED BY DEFAULT AS IDENTITY,
  empleado_id      NUMBER NOT NULL,
  cargo_id         NUMBER NOT NULL,
  salario_base_gs  NUMBER(14,2) NOT NULL,
  vigente_desde    DATE NOT NULL,
  vigente_hasta    DATE
);

ALTER TABLE ingesoft.empleado_cargo_hist ADD CONSTRAINT pk_empleado_cargo_hist PRIMARY KEY (cod_empleado_cargo_hist);
ALTER TABLE ingesoft.empleado_cargo_hist ADD CONSTRAINT fk_ech_empleado FOREIGN KEY (empleado_id) REFERENCES ingesoft.empleado(cod_empleado);
ALTER TABLE ingesoft.empleado_cargo_hist ADD CONSTRAINT fk_ech_cargo    FOREIGN KEY (cargo_id)    REFERENCES ingesoft.cargo(cod_cargo);

CREATE INDEX ingesoft.ix_ech_empleado         ON ingesoft.empleado_cargo_hist(empleado_id);