CREATE TABLE ingesoft.empleado_concepto (
  cod_empleado_concepto NUMBER GENERATED BY DEFAULT AS IDENTITY,
  empleado_id           NUMBER NOT NULL,
  concepto_id           NUMBER NOT NULL,
  monto_fijo_gs         NUMBER(14,2),
  porc                  NUMBER(9,4),
  vigente_desde         DATE NOT NULL,
  vigente_hasta         DATE
);

ALTER TABLE ingesoft.empleado_concepto ADD CONSTRAINT pk_empleado_concepto PRIMARY KEY (cod_empleado_concepto);
ALTER TABLE ingesoft.empleado_concepto ADD CONSTRAINT uq_emp_conc_fecha UNIQUE (empleado_id, concepto_id, vigente_desde);
ALTER TABLE ingesoft.empleado_concepto ADD CONSTRAINT fk_emp_conc_empleado FOREIGN KEY (empleado_id) REFERENCES ingesoft.empleado(cod_empleado);
ALTER TABLE ingesoft.empleado_concepto ADD CONSTRAINT fk_emp_conc_concepto FOREIGN KEY (concepto_id) REFERENCES ingesoft.concepto(cod_concepto);

CREATE INDEX ingesoft.ix_emp_conc_empleado    ON ingesoft.empleado_concepto(empleado_id);