CREATE TABLE ingesoft.estado_civil (
  cod_estado_civil NUMBER GENERATED BY DEFAULT AS IDENTITY,
  codigo           VARCHAR2(20)   NOT NULL,
  descripcion      VARCHAR2(100)  NOT NULL
);

ALTER TABLE ingesoft.estado_civil ADD CONSTRAINT pk_estado_civil PRIMARY KEY (cod_estado_civil);
ALTER TABLE ingesoft.estado_civil ADD CONSTRAINT uq_estado_civil_codigo UNIQUE (codigo);
