CREATE TABLE ingesoft.hijo (
  cod_hijo     NUMBER GENERATED BY DEFAULT AS IDENTITY,
  empleado_id  NUMBER NOT NULL,
  nombre       VARCHAR2(100) NOT NULL,
  fecha_nac    DATE NOT NULL,
  discapacidad VARCHAR2(1) DEFAULT 'N' NOT NULL,
  reside_py    VARCHAR2(1) DEFAULT 'S' NOT NULL
);

ALTER TABLE ingesoft.hijo ADD CONSTRAINT pk_hijo PRIMARY KEY (cod_hijo);
ALTER TABLE ingesoft.hijo ADD CONSTRAINT ck_hijo_disc CHECK (discapacidad IN ('S','N'));
ALTER TABLE ingesoft.hijo ADD CONSTRAINT ck_hijo_reside CHECK (reside_py IN ('S','N'));
ALTER TABLE ingesoft.hijo ADD CONSTRAINT fk_hijo_empleado FOREIGN KEY (empleado_id) REFERENCES ingesoft.empleado(cod_empleado);

CREATE INDEX ingesoft.ix_hijo_empleado        ON ingesoft.hijo(empleado_id);