CREATE TABLE ingesoft.hijo_doc (
  cod_hijo_doc  NUMBER GENERATED BY DEFAULT AS IDENTITY,
  hijo_id       NUMBER NOT NULL,
  tipo          VARCHAR2(30) NOT NULL,
  fecha_emision DATE NOT NULL,
  fecha_venc    DATE,
  archivo_id    NUMBER,
  valido        VARCHAR2(1) DEFAULT 'S' NOT NULL
);

ALTER TABLE ingesoft.hijo_doc ADD CONSTRAINT pk_hijo_doc PRIMARY KEY (cod_hijo_doc);
ALTER TABLE ingesoft.hijo_doc ADD CONSTRAINT ck_hijo_doc_tipo CHECK (tipo IN ('NACIMIENTO','VIDA_RESIDENCIA'));
ALTER TABLE ingesoft.hijo_doc ADD CONSTRAINT ck_hijo_doc_valido CHECK (valido IN ('S','N'));
ALTER TABLE ingesoft.hijo_doc ADD CONSTRAINT fk_hijo_doc_hijo    FOREIGN KEY (hijo_id)    REFERENCES ingesoft.hijo(cod_hijo);
ALTER TABLE ingesoft.hijo_doc ADD CONSTRAINT fk_hijo_doc_archivo FOREIGN KEY (archivo_id) REFERENCES ingesoft.adjunto(cod_adjunto);
