CREATE TABLE ingesoft.horas_extra (
  cod_horas_extra NUMBER GENERATED BY DEFAULT AS IDENTITY,
  empleado_id     NUMBER NOT NULL,
  fecha           DATE   NOT NULL,
  horas           NUMBER(6,2) NOT NULL,
  factor          NUMBER(5,2) DEFAULT 1.50 NOT NULL
);

ALTER TABLE ingesoft.horas_extra ADD CONSTRAINT pk_horas_extra PRIMARY KEY (cod_horas_extra);
ALTER TABLE ingesoft.horas_extra ADD CONSTRAINT fk_hextra_empleado FOREIGN KEY (empleado_id) REFERENCES ingesoft.empleado(cod_empleado);

CREATE INDEX ingesoft.ix_hextra_empleado      ON ingesoft.horas_extra(empleado_id);