CREATE TABLE ingesoft.nomina_detalle (
  cod_nomina_detalle NUMBER GENERATED BY DEFAULT AS IDENTITY,
  proceso_id      NUMBER NOT NULL,
  empleado_id     NUMBER NOT NULL,
  concepto_id     NUMBER NOT NULL,
  cantidad        NUMBER(12,4) DEFAULT 1,
  monto_unit_gs   NUMBER(14,2) NOT NULL,
  monto_total_gs  NUMBER(14,2) NOT NULL,
  imponible_ips   VARCHAR2(1) DEFAULT 'S' NOT NULL,
  afecta_aguinaldo VARCHAR2(1) DEFAULT 'S' NOT NULL
);

ALTER TABLE ingesoft.nomina_detalle ADD CONSTRAINT pk_nomina_detalle PRIMARY KEY (cod_nomina_detalle);
ALTER TABLE ingesoft.nomina_detalle ADD CONSTRAINT ck_nd_flags CHECK (imponible_ips IN ('S','N') AND afecta_aguinaldo IN ('S','N'));
ALTER TABLE ingesoft.nomina_detalle ADD CONSTRAINT fk_nd_proceso  FOREIGN KEY (proceso_id)  REFERENCES ingesoft.proceso_nomina(cod_proceso_nomina);
ALTER TABLE ingesoft.nomina_detalle ADD CONSTRAINT fk_nd_empleado FOREIGN KEY (empleado_id) REFERENCES ingesoft.empleado(cod_empleado);
ALTER TABLE ingesoft.nomina_detalle ADD CONSTRAINT fk_nd_concepto FOREIGN KEY (concepto_id) REFERENCES ingesoft.concepto(cod_concepto);

CREATE INDEX ingesoft.ix_nd_empleado          ON ingesoft.nomina_detalle(empleado_id);
CREATE INDEX ingesoft.ix_nd_concepto          ON ingesoft.nomina_detalle(concepto_id);