CREATE TABLE ingesoft.parametro_sistema (
  cod_parametro_sistema NUMBER GENERATED BY DEFAULT AS IDENTITY,
  codigo      VARCHAR2(60)   NOT NULL,
  valor       VARCHAR2(4000) NOT NULL,
  descripcion VARCHAR2(200)
);

ALTER TABLE ingesoft.parametro_sistema ADD CONSTRAINT pk_parametro_sistema PRIMARY KEY (cod_parametro_sistema);
ALTER TABLE ingesoft.parametro_sistema ADD CONSTRAINT uq_parametro_codigo UNIQUE (codigo);
