CREATE TABLE ingesoft.periodo_nomina (
  cod_periodo_nomina NUMBER GENERATED BY DEFAULT AS IDENTITY,
  anio          NUMBER NOT NULL,
  mes           NUMBER NOT NULL,
  fecha_inicio  DATE   NOT NULL,
  fecha_fin     DATE   NOT NULL,
  estado        VARCHAR2(15) DEFAULT 'ABIERTO' NOT NULL
);

ALTER TABLE ingesoft.periodo_nomina ADD CONSTRAINT pk_periodo_nomina PRIMARY KEY (cod_periodo_nomina);
ALTER TABLE ingesoft.periodo_nomina ADD CONSTRAINT uq_periodo_anio_mes UNIQUE (anio, mes);
ALTER TABLE ingesoft.periodo_nomina ADD CONSTRAINT ck_periodo_estado CHECK (estado IN ('ABIERTO','PROCESADO','CERRADO'));
ALTER TABLE ingesoft.periodo_nomina ADD CONSTRAINT ck_periodo_mes CHECK (mes BETWEEN 1 AND 12);
