CREATE TABLE ingesoft.permiso (
  cod_permiso  NUMBER GENERATED BY DEFAULT AS IDENTITY,
  codigo       VARCHAR2(60)  NOT NULL,
  descripcion  VARCHAR2(200)
);

ALTER TABLE ingesoft.permiso ADD CONSTRAINT pk_permiso PRIMARY KEY (cod_permiso);
ALTER TABLE ingesoft.permiso ADD CONSTRAINT uq_permiso_codigo UNIQUE (codigo);