CREATE TABLE ingesoft.persona (
  cod_persona   NUMBER GENERATED BY DEFAULT AS IDENTITY,
  ci                VARCHAR2(20)   NOT NULL,
  nombre            VARCHAR2(100)  NOT NULL,
  apellido          VARCHAR2(100)  NOT NULL,
  fecha_nacimiento  DATE           NOT NULL,
  estado_civil_id   NUMBER,
  email             VARCHAR2(150),
  telefono          VARCHAR2(50),
  direccion         VARCHAR2(200)
);

ALTER TABLE ingesoft.persona ADD CONSTRAINT pk_persona PRIMARY KEY (cod_persona);
ALTER TABLE ingesoft.persona ADD CONSTRAINT uq_persona_ci UNIQUE (ci);
ALTER TABLE ingesoft.persona ADD CONSTRAINT fk_persona_estado_civil
  FOREIGN KEY (estado_civil_id) REFERENCES ingesoft.estado_civil(cod_estado_civil);
