CREATE TABLE ingesoft.prestamo (
  cod_prestamo    NUMBER GENERATED BY DEFAULT AS IDENTITY,
  empleado_id     NUMBER NOT NULL,
  fecha_otorg     DATE   NOT NULL,
  monto_gs        NUMBER(14,2) NOT NULL,
  tasa_anual      NUMBER(7,4),
  cuotas          NUMBER NOT NULL,
  saldo_pend_gs   NUMBER(14,2) NOT NULL
);

ALTER TABLE ingesoft.prestamo ADD CONSTRAINT pk_prestamo PRIMARY KEY (cod_prestamo);
ALTER TABLE ingesoft.prestamo ADD CONSTRAINT fk_prestamo_empleado FOREIGN KEY (empleado_id) REFERENCES ingesoft.empleado(cod_empleado);

CREATE INDEX ingesoft.ix_prestamo_empleado    ON ingesoft.prestamo(empleado_id);