CREATE TABLE ingesoft.prestamo_cronograma (
  cod_prestamo_cronograma NUMBER GENERATED BY DEFAULT AS IDENTITY,
  prestamo_id  NUMBER NOT NULL,
  nro_cuota    NUMBER NOT NULL,
  vencimiento  DATE   NOT NULL,
  capital_gs   NUMBER(14,2) NOT NULL,
  interes_gs   NUMBER(14,2) NOT NULL,
  pagado       VARCHAR2(1) DEFAULT 'N' NOT NULL
);

ALTER TABLE ingesoft.prestamo_cronograma ADD CONSTRAINT pk_prestamo_cronograma PRIMARY KEY (cod_prestamo_cronograma);
ALTER TABLE ingesoft.prestamo_cronograma ADD CONSTRAINT uq_prestamo_cuota UNIQUE (prestamo_id, nro_cuota);
ALTER TABLE ingesoft.prestamo_cronograma ADD CONSTRAINT ck_prestamo_pagado CHECK (pagado IN ('S','N'));
ALTER TABLE ingesoft.prestamo_cronograma ADD CONSTRAINT fk_precron_prestamo FOREIGN KEY (prestamo_id) REFERENCES ingesoft.prestamo(cod_prestamo);
