CREATE TABLE ingesoft.proceso_nomina (
  cod_proceso_nomina NUMBER GENERATED BY DEFAULT AS IDENTITY,
  periodo_id      NUMBER NOT NULL,
  ejecutado_por   NUMBER,
  fecha_ejecucion DATE,
  estado          VARCHAR2(15) DEFAULT 'PROCESADO' NOT NULL
);

ALTER TABLE ingesoft.proceso_nomina ADD CONSTRAINT pk_proceso_nomina PRIMARY KEY (cod_proceso_nomina);
ALTER TABLE ingesoft.proceso_nomina ADD CONSTRAINT ck_proc_estado CHECK (estado IN ('PROCESADO','ANULADO'));
ALTER TABLE ingesoft.proceso_nomina ADD CONSTRAINT fk_proc_periodo FOREIGN KEY (periodo_id) REFERENCES ingesoft.periodo_nomina(cod_periodo_nomina);
ALTER TABLE ingesoft.proceso_nomina ADD CONSTRAINT fk_proc_usuario FOREIGN KEY (ejecutado_por) REFERENCES ingesoft.usuario(cod_usuario);
