CREATE TABLE ingesoft.recibo_detalle (
  cod_recibo_detalle NUMBER GENERATED BY DEFAULT AS IDENTITY,
  recibo_id   NUMBER NOT NULL,
  concepto_id NUMBER NOT NULL,
  descripcion VARCHAR2(150),
  monto_gs    NUMBER(14,2) NOT NULL
);

ALTER TABLE ingesoft.recibo_detalle ADD CONSTRAINT pk_recibo_detalle PRIMARY KEY (cod_recibo_detalle);
ALTER TABLE ingesoft.recibo_detalle ADD CONSTRAINT fk_recibo_det_recibo  FOREIGN KEY (recibo_id)  REFERENCES ingesoft.recibo(cod_recibo);
ALTER TABLE ingesoft.recibo_detalle ADD CONSTRAINT fk_recibo_det_concepto FOREIGN KEY (concepto_id) REFERENCES ingesoft.concepto(cod_concepto);
