CREATE TABLE ingesoft.recibo (
  cod_recibo        NUMBER GENERATED BY DEFAULT AS IDENTITY,
  proceso_id        NUMBER NOT NULL,
  empleado_id       NUMBER NOT NULL,
  total_ingresos    NUMBER(14,2) NOT NULL,
  total_descuentos  NUMBER(14,2) NOT NULL,
  neto_cobrar       NUMBER(14,2) NOT NULL,
  neto_letras       VARCHAR2(400),
  fecha_emision     DATE,
  estado            VARCHAR2(15) DEFAULT 'EMITIDO' NOT NULL
);

ALTER TABLE ingesoft.recibo ADD CONSTRAINT pk_recibo PRIMARY KEY (cod_recibo);
ALTER TABLE ingesoft.recibo ADD CONSTRAINT uq_recibo_proc_emp UNIQUE (proceso_id, empleado_id);
ALTER TABLE ingesoft.recibo ADD CONSTRAINT ck_recibo_estado CHECK (estado IN ('EMITIDO','ANULADO'));
ALTER TABLE ingesoft.recibo ADD CONSTRAINT fk_recibo_proceso  FOREIGN KEY (proceso_id)  REFERENCES ingesoft.proceso_nomina(cod_proceso_nomina);
ALTER TABLE ingesoft.recibo ADD CONSTRAINT fk_recibo_empleado FOREIGN KEY (empleado_id) REFERENCES ingesoft.empleado(cod_empleado);

CREATE INDEX ingesoft.ix_recibo_empleado      ON ingesoft.recibo(empleado_id);