CREATE TABLE ingesoft.rol (
  cod_rol      NUMBER GENERATED BY DEFAULT AS IDENTITY,
  codigo       VARCHAR2(40)  NOT NULL,
  descripcion  VARCHAR2(120)
);

ALTER TABLE ingesoft.rol ADD CONSTRAINT pk_rol PRIMARY KEY (cod_rol);
ALTER TABLE ingesoft.rol ADD CONSTRAINT uq_rol_codigo UNIQUE (codigo);
