CREATE TABLE ingesoft.rol_permiso (
  cod_rol_permiso NUMBER GENERATED BY DEFAULT AS IDENTITY,
  rol_id          NUMBER NOT NULL,
  permiso_id      NUMBER NOT NULL
);

ALTER TABLE ingesoft.rol_permiso ADD CONSTRAINT pk_rol_permiso PRIMARY KEY (cod_rol_permiso);
ALTER TABLE ingesoft.rol_permiso ADD CONSTRAINT uq_rol_permiso UNIQUE (rol_id, permiso_id);
ALTER TABLE ingesoft.rol_permiso ADD CONSTRAINT fk_rol_permiso_rol     FOREIGN KEY (rol_id)     REFERENCES ingesoft.rol(cod_rol);
ALTER TABLE ingesoft.rol_permiso ADD CONSTRAINT fk_rol_permiso_permiso FOREIGN KEY (permiso_id) REFERENCES ingesoft.permiso(cod_permiso);
