CREATE TABLE ingesoft.salario_minimo_hist (
  cod_salario_minimo_hist NUMBER GENERATED BY DEFAULT AS IDENTITY,
  vigente_desde   DATE   NOT NULL,
  vigente_hasta   DATE,
  monto_gs        NUMBER(14,2) NOT NULL
);

ALTER TABLE ingesoft.salario_minimo_hist ADD CONSTRAINT pk_salario_minimo_hist PRIMARY KEY (cod_salario_minimo_hist);
ALTER TABLE ingesoft.salario_minimo_hist ADD CONSTRAINT uq_salario_minimo_desde UNIQUE (vigente_desde);
