CREATE TABLE ingesoft.tipo_ausencia (
  cod_tipo_ausencia NUMBER GENERATED BY DEFAULT AS IDENTITY,
  descripcion       VARCHAR2(60)
);

ALTER TABLE ingesoft.tipo_ausencia ADD CONSTRAINT pk_tipo_ausencia PRIMARY KEY (cod_tipo_ausencia);
