CREATE TABLE ingesoft.usuario (
  cod_usuario    NUMBER GENERATED BY DEFAULT AS IDENTITY,
  username       VARCHAR2(80)  NOT NULL,
  hash_password  VARCHAR2(200) NOT NULL,
  empleado_id    NUMBER,
  activo         VARCHAR2(1) DEFAULT 'S' NOT NULL
);

ALTER TABLE ingesoft.usuario ADD CONSTRAINT pk_usuario PRIMARY KEY (cod_usuario);
ALTER TABLE ingesoft.usuario ADD CONSTRAINT uq_usuario_username UNIQUE (username);
ALTER TABLE ingesoft.usuario ADD CONSTRAINT ck_usuario_activo CHECK (activo IN ('S','N'));
ALTER TABLE ingesoft.usuario ADD CONSTRAINT fk_usuario_empleado FOREIGN KEY (empleado_id) REFERENCES ingesoft.empleado(cod_empleado);

CREATE INDEX ingesoft.ix_usuario_empleado     ON ingesoft.usuario(empleado_id);