CREATE TABLE ingesoft.usuario_rol (
  cod_usuario_rol NUMBER GENERATED BY DEFAULT AS IDENTITY,
  usuario_id      NUMBER NOT NULL,
  rol_id          NUMBER NOT NULL
);

ALTER TABLE ingesoft.usuario_rol ADD CONSTRAINT pk_usuario_rol PRIMARY KEY (cod_usuario_rol);
ALTER TABLE ingesoft.usuario_rol ADD CONSTRAINT uq_usuario_rol UNIQUE (usuario_id, rol_id);
ALTER TABLE ingesoft.usuario_rol ADD CONSTRAINT fk_usuario_rol_usuario FOREIGN KEY (usuario_id) REFERENCES ingesoft.usuario(cod_usuario);
ALTER TABLE ingesoft.usuario_rol ADD CONSTRAINT fk_usuario_rol_rol     FOREIGN KEY (rol_id)     REFERENCES ingesoft.rol(cod_rol);
